<?php

namespace ContainerOfKhxAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DCNpF2sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dCNpF2s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dCNpF2s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'gemini' => ['privates', 'App\\service\\GeminiService', 'getGeminiServiceService', true],
        ], [
            'em' => '?',
            'gemini' => 'App\\service\\GeminiService',
        ]);
    }
}
