<?php

namespace ContainerOfKhxAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_1lqa8HUService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.1lqa8HU' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.1lqa8HU'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\ActivityController::log' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\TestDbController::testDatabase' => ['privates', '.service_locator.hUbu2Ln', 'get_ServiceLocator_HUbu2LnService', true],
            'App\\Controller\\admin\\AdminController::banUser' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\admin\\AdminController::editUser' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\admin\\AdminController::updatePassword' => ['privates', '.service_locator.81LTOQ7', 'get_ServiceLocator_81LTOQ7Service', true],
            'App\\Controller\\admin\\AdminController::updateProfile' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\user\\AuthController::login' => ['privates', '.service_locator.VIY6kUB', 'get_ServiceLocator_VIY6kUBService', true],
            'App\\Controller\\user\\AuthController::onboarding' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\user\\AuthController::register' => ['privates', '.service_locator.81LTOQ7', 'get_ServiceLocator_81LTOQ7Service', true],
            'App\\Controller\\user\\AuthController::savePreferences' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\user\\ChatController::chat' => ['privates', '.service_locator.dCNpF2s', 'get_ServiceLocator_DCNpF2sService', true],
            'App\\Controller\\user\\TestGeminiController::test' => ['privates', '.service_locator.ZBf0eUd', 'get_ServiceLocator_ZBf0eUdService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\ActivityController:log' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\TestDbController:testDatabase' => ['privates', '.service_locator.hUbu2Ln', 'get_ServiceLocator_HUbu2LnService', true],
            'App\\Controller\\admin\\AdminController:banUser' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\admin\\AdminController:editUser' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\admin\\AdminController:updatePassword' => ['privates', '.service_locator.81LTOQ7', 'get_ServiceLocator_81LTOQ7Service', true],
            'App\\Controller\\admin\\AdminController:updateProfile' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\user\\AuthController:login' => ['privates', '.service_locator.VIY6kUB', 'get_ServiceLocator_VIY6kUBService', true],
            'App\\Controller\\user\\AuthController:onboarding' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\user\\AuthController:register' => ['privates', '.service_locator.81LTOQ7', 'get_ServiceLocator_81LTOQ7Service', true],
            'App\\Controller\\user\\AuthController:savePreferences' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\user\\ChatController:chat' => ['privates', '.service_locator.dCNpF2s', 'get_ServiceLocator_DCNpF2sService', true],
            'App\\Controller\\user\\TestGeminiController:test' => ['privates', '.service_locator.ZBf0eUd', 'get_ServiceLocator_ZBf0eUdService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\ActivityController::log' => '?',
            'App\\Controller\\TestDbController::testDatabase' => '?',
            'App\\Controller\\admin\\AdminController::banUser' => '?',
            'App\\Controller\\admin\\AdminController::editUser' => '?',
            'App\\Controller\\admin\\AdminController::updatePassword' => '?',
            'App\\Controller\\admin\\AdminController::updateProfile' => '?',
            'App\\Controller\\user\\AuthController::login' => '?',
            'App\\Controller\\user\\AuthController::onboarding' => '?',
            'App\\Controller\\user\\AuthController::register' => '?',
            'App\\Controller\\user\\AuthController::savePreferences' => '?',
            'App\\Controller\\user\\ChatController::chat' => '?',
            'App\\Controller\\user\\TestGeminiController::test' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ActivityController:log' => '?',
            'App\\Controller\\TestDbController:testDatabase' => '?',
            'App\\Controller\\admin\\AdminController:banUser' => '?',
            'App\\Controller\\admin\\AdminController:editUser' => '?',
            'App\\Controller\\admin\\AdminController:updatePassword' => '?',
            'App\\Controller\\admin\\AdminController:updateProfile' => '?',
            'App\\Controller\\user\\AuthController:login' => '?',
            'App\\Controller\\user\\AuthController:onboarding' => '?',
            'App\\Controller\\user\\AuthController:register' => '?',
            'App\\Controller\\user\\AuthController:savePreferences' => '?',
            'App\\Controller\\user\\ChatController:chat' => '?',
            'App\\Controller\\user\\TestGeminiController:test' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
