<?php

namespace ContainerOfKhxAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDestinationServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\service\DestinationService' shared autowired service.
     *
     * @return \App\service\DestinationService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\service\\DestinationService'] = new \App\service\DestinationService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
