<?php

namespace ContainerOfKhxAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\user\FrontController' shared autowired service.
     *
     * @return \App\Controller\user\FrontController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\user\\FrontController'] = $instance = new \App\Controller\user\FrontController(($container->privates['App\\service\\UserProfileService'] ?? $container->load('getUserProfileServiceService')), ($container->privates['App\\service\\DestinationService'] ?? $container->load('getDestinationServiceService')), ($container->privates['App\\service\\ActivityService'] ?? $container->load('getActivityServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\user\\FrontController', $container));

        return $instance;
    }
}
