<?php

namespace ContainerOfKhxAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFixAdminCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\FixAdminCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\FixAdminCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('app:fix-admin', [], 'Creates or fixes the admin user', false, #[\Closure(name: 'App\\Command\\FixAdminCommand')] fn (): \App\Command\FixAdminCommand => ($container->privates['App\\Command\\FixAdminCommand'] ?? $container->load('getFixAdminCommandService')));
    }
}
