<?php

namespace ContainerOfKhxAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHashPasswordsCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\HashPasswordsCommand' shared autowired service.
     *
     * @return \App\Command\HashPasswordsCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\HashPasswordsCommand'] = $instance = new \App\Command\HashPasswordsCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setName('app:hash-passwords');
        $instance->setDescription('Hash all plain text passwords');

        return $instance;
    }
}
