<?php

namespace ContainerOfKhxAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserActivityLogRepositoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Repository\UserActivityLogRepository' shared autowired service.
     *
     * @return \App\Repository\UserActivityLogRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\UserActivityLogRepository'] = new \App\Repository\UserActivityLogRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
