<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260411173231 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE community_statistics DROP FOREIGN KEY fk_stats_user');
        $this->addSql('DROP TABLE community_statistics');
        $this->addSql('DROP TABLE reports');
        $this->addSql('ALTER TABLE accommodation CHANGE description description LONGTEXT DEFAULT NULL, CHANGE accommodation_amenities accommodation_amenities LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE activities DROP FOREIGN KEY activities_ibfk_1');
        $this->addSql('ALTER TABLE activities DROP FOREIGN KEY activities_ibfk_1');
        $this->addSql('ALTER TABLE activities CHANGE activity_id activity_id BIGINT AUTO_INCREMENT NOT NULL, CHANGE destination_id destination_id BIGINT NOT NULL, CHANGE category category VARCHAR(50) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE duration_minutes duration_minutes SMALLINT NOT NULL, CHANGE currency currency VARCHAR(3) DEFAULT \'USD\' NOT NULL, CHANGE age_min age_min SMALLINT DEFAULT NULL, CHANGE capacity capacity SMALLINT NOT NULL');
        $this->addSql('ALTER TABLE activities ADD CONSTRAINT FK_B5F1AFE5816C6140 FOREIGN KEY (destination_id) REFERENCES destinations (destination_id)');
        $this->addSql('DROP INDEX destination_id ON activities');
        $this->addSql('CREATE INDEX IDX_B5F1AFE5816C6140 ON activities (destination_id)');
        $this->addSql('ALTER TABLE activities ADD CONSTRAINT activities_ibfk_1 FOREIGN KEY (destination_id) REFERENCES destinations (destination_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bookingacc DROP FOREIGN KEY fk_bookingacc_user');
        $this->addSql('ALTER TABLE bookingacc DROP FOREIGN KEY fk_bookingacc_room');
        $this->addSql('DROP INDEX idx_bookingacc_status_created ON bookingacc');
        $this->addSql('DROP INDEX idx_bookingacc_room_status_dates ON bookingacc');
        $this->addSql('DROP INDEX idx_bookingacc_user_created ON bookingacc');
        $this->addSql('DROP INDEX IDX_494EA9D3A76ED395 ON bookingacc');
        $this->addSql('ALTER TABLE bookingacc CHANGE special_requests special_requests LONGTEXT DEFAULT NULL, CHANGE cancel_reason cancel_reason LONGTEXT DEFAULT NULL, CHANGE rejection_reason rejection_reason LONGTEXT DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT \'PENDING\', CHANGE calendar_sync_status calendar_sync_status VARCHAR(20) DEFAULT \'NOT_SYNCED\' NOT NULL, CHANGE calendar_last_error calendar_last_error LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE bookingacc ADD CONSTRAINT FK_494EA9D354177093 FOREIGN KEY (room_id) REFERENCES room (id)');
        $this->addSql('ALTER TABLE bookingdes DROP FOREIGN KEY bookingdes_ibfk_3');
        $this->addSql('ALTER TABLE bookingdes DROP FOREIGN KEY bookingdes_ibfk_1');
        $this->addSql('ALTER TABLE bookingdes DROP FOREIGN KEY bookingdes_ibfk_2');
        $this->addSql('DROP INDEX activity_id ON bookingdes');
        $this->addSql('DROP INDEX user_id ON bookingdes');
        $this->addSql('DROP INDEX destination_id ON bookingdes');
        $this->addSql('ALTER TABLE bookingdes CHANGE booking_id booking_id BIGINT AUTO_INCREMENT NOT NULL, CHANGE destination_id destination_id BIGINT DEFAULT NULL, CHANGE activity_id activity_id BIGINT DEFAULT NULL, CHANGE num_guests num_guests SMALLINT DEFAULT 1 NOT NULL, CHANGE status status VARCHAR(20) DEFAULT \'pending\' NOT NULL, CHANGE payment_status payment_status VARCHAR(20) DEFAULT \'unpaid\' NOT NULL, CHANGE currency currency VARCHAR(3) DEFAULT \'USD\' NOT NULL, CHANGE notes notes LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE bookingtrans DROP FOREIGN KEY bookingtrans_ibfk_3');
        $this->addSql('ALTER TABLE bookingtrans DROP FOREIGN KEY bookingtrans_ibfk_1');
        $this->addSql('ALTER TABLE bookingtrans DROP FOREIGN KEY bookingtrans_ibfk_2');
        $this->addSql('DROP INDEX transport_id ON bookingtrans');
        $this->addSql('DROP INDEX schedule_id ON bookingtrans');
        $this->addSql('DROP INDEX user_id ON bookingtrans');
        $this->addSql('ALTER TABLE bookingtrans CHANGE booking_date booking_date DATETIME DEFAULT NULL, CHANGE adults_count adults_count INT NOT NULL, CHANGE children_count children_count INT NOT NULL, CHANGE total_price total_price DOUBLE PRECISION NOT NULL, CHANGE booking_status booking_status VARCHAR(255) NOT NULL, CHANGE payment_status payment_status VARCHAR(255) NOT NULL, CHANGE insurance_included insurance_included TINYINT(1) NOT NULL, CHANGE ai_price_prediction ai_price_prediction DOUBLE PRECISION NOT NULL, CHANGE comparison_score comparison_score DOUBLE PRECISION NOT NULL, CHANGE cancellation_reason cancellation_reason VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY comments_ibfk_1');
        $this->addSql('DROP INDEX comments_ibfk_1 ON comments');
        $this->addSql('ALTER TABLE comments CHANGE body body LONGTEXT NOT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT FK_5F9E962A4B89032C FOREIGN KEY (post_id) REFERENCES posts (id)');
        $this->addSql('CREATE INDEX IDX_5F9E962A4B89032C ON comments (post_id)');
        $this->addSql('ALTER TABLE destination_trans DROP created_at, CHANGE name name VARCHAR(255) NOT NULL, CHANGE type type VARCHAR(100) NOT NULL, CHANGE city city VARCHAR(100) NOT NULL, CHANGE best_season best_season VARCHAR(50) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE average_rating average_rating DOUBLE PRECISION NOT NULL');
        $this->addSql('ALTER TABLE destinations CHANGE destination_id destination_id BIGINT AUTO_INCREMENT NOT NULL, CHANGE type type VARCHAR(50) NOT NULL, CHANGE best_season best_season VARCHAR(20) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE popularity popularity INT DEFAULT 0 NOT NULL');
        $this->addSql('ALTER TABLE followings DROP FOREIGN KEY followings_ibfk_1');
        $this->addSql('ALTER TABLE followings DROP FOREIGN KEY followings_ibfk_2');
        $this->addSql('DROP INDEX followings_ibfk_2 ON followings');
        $this->addSql('DROP INDEX followings_ibfk_1 ON followings');
        $this->addSql('ALTER TABLE followings CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE loyalty_points DROP FOREIGN KEY loyalty_points_ibfk_1');
        $this->addSql('DROP INDEX user_id ON loyalty_points');
        $this->addSql('ALTER TABLE loyalty_points CHANGE user_id user_id INT NOT NULL, CHANGE total_points total_points INT DEFAULT 0 NOT NULL, CHANGE level level VARCHAR(20) DEFAULT \'BRONZE\' NOT NULL');
        $this->addSql('ALTER TABLE offers DROP FOREIGN KEY offers_ibfk_1');
        $this->addSql('ALTER TABLE offers DROP FOREIGN KEY offers_ibfk_2');
        $this->addSql('ALTER TABLE offers DROP FOREIGN KEY offers_ibfk_3');
        $this->addSql('DROP INDEX accommodation_id ON offers');
        $this->addSql('DROP INDEX pack_id ON offers');
        $this->addSql('DROP INDEX destination_id ON offers');
        $this->addSql('ALTER TABLE offers CHANGE destination_id destination_id BIGINT DEFAULT NULL, CHANGE title title VARCHAR(255) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE discount_type discount_type VARCHAR(20) NOT NULL, CHANGE discount_value discount_value NUMERIC(10, 2) NOT NULL, CHANGE start_date start_date DATE NOT NULL, CHANGE end_date end_date DATE NOT NULL, CHANGE is_active is_active TINYINT(1) DEFAULT 1 NOT NULL');
        $this->addSql('ALTER TABLE packs DROP FOREIGN KEY packs_ibfk_1');
        $this->addSql('ALTER TABLE packs DROP FOREIGN KEY packs_ibfk_4');
        $this->addSql('ALTER TABLE packs DROP FOREIGN KEY packs_ibfk_2');
        $this->addSql('ALTER TABLE packs DROP FOREIGN KEY packs_ibfk_5');
        $this->addSql('ALTER TABLE packs DROP FOREIGN KEY packs_ibfk_3');
        $this->addSql('DROP INDEX accommodation_id ON packs');
        $this->addSql('DROP INDEX activity_id ON packs');
        $this->addSql('DROP INDEX transport_id ON packs');
        $this->addSql('DROP INDEX destination_id ON packs');
        $this->addSql('DROP INDEX category_id ON packs');
        $this->addSql('ALTER TABLE packs CHANGE destination_id destination_id BIGINT DEFAULT NULL, CHANGE activity_id activity_id BIGINT DEFAULT NULL, CHANGE title title VARCHAR(255) NOT NULL, CHANGE description description LONGTEXT DEFAULT NULL, CHANGE duration_days duration_days INT NOT NULL, CHANGE base_price base_price NUMERIC(10, 2) NOT NULL, CHANGE status status VARCHAR(20) DEFAULT \'ACTIVE\' NOT NULL');
        $this->addSql('ALTER TABLE packs_bookings DROP FOREIGN KEY packs_bookings_ibfk_2');
        $this->addSql('ALTER TABLE packs_bookings DROP FOREIGN KEY packs_bookings_ibfk_1');
        $this->addSql('DROP INDEX idx_booking_date ON packs_bookings');
        $this->addSql('DROP INDEX idx_status ON packs_bookings');
        $this->addSql('DROP INDEX idx_user_id ON packs_bookings');
        $this->addSql('DROP INDEX idx_pack_id ON packs_bookings');
        $this->addSql('ALTER TABLE packs_bookings CHANGE num_travelers num_travelers INT NOT NULL, CHANGE discount_applied discount_applied NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, CHANGE status status VARCHAR(20) DEFAULT \'PENDING\' NOT NULL, CHANGE notes notes LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE posts DROP FOREIGN KEY posts_ibfk_1');
        $this->addSql('DROP INDEX posts_ibfk_1 ON posts');
        $this->addSql('ALTER TABLE posts CHANGE body body LONGTEXT NOT NULL, CHANGE type type VARCHAR(50) NOT NULL, CHANGE image_url image_url VARCHAR(1000) DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL, CHANGE is_confirmed is_confirmed TINYINT(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE price_alerts DROP FOREIGN KEY price_alerts_ibfk_1');
        $this->addSql('ALTER TABLE price_alerts DROP FOREIGN KEY price_alerts_ibfk_2');
        $this->addSql('DROP INDEX user_id ON price_alerts');
        $this->addSql('DROP INDEX activity_id ON price_alerts');
        $this->addSql('ALTER TABLE price_alerts CHANGE activity_id activity_id BIGINT NOT NULL, CHANGE direction direction VARCHAR(4) NOT NULL, CHANGE is_active is_active TINYINT(1) DEFAULT 1 NOT NULL, CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE reactions DROP FOREIGN KEY fk_reactions_post');
        $this->addSql('ALTER TABLE reactions DROP FOREIGN KEY fk_reactions_story');
        $this->addSql('ALTER TABLE reactions DROP FOREIGN KEY fk_reactions_comment');
        $this->addSql('DROP INDEX fk_reactions_story ON reactions');
        $this->addSql('DROP INDEX idx_reactions_post ON reactions');
        $this->addSql('DROP INDEX idx_reactions_comment ON reactions');
        $this->addSql('ALTER TABLE reactions CHANGE type type VARCHAR(20) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE room DROP FOREIGN KEY room_ibfk_1');
        $this->addSql('ALTER TABLE room DROP FOREIGN KEY room_ibfk_1');
        $this->addSql('ALTER TABLE room CHANGE amenities amenities LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519B8F3692CD FOREIGN KEY (accommodation_id) REFERENCES accommodation (id)');
        $this->addSql('DROP INDEX accommodation_id ON room');
        $this->addSql('CREATE INDEX IDX_729F519B8F3692CD ON room (accommodation_id)');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT room_ibfk_1 FOREIGN KEY (accommodation_id) REFERENCES accommodation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE room_images DROP FOREIGN KEY fk_room_images_room');
        $this->addSql('ALTER TABLE room_images DROP FOREIGN KEY fk_room_images_room');
        $this->addSql('ALTER TABLE room_images ADD CONSTRAINT FK_A15178AB54177093 FOREIGN KEY (room_id) REFERENCES room (id)');
        $this->addSql('DROP INDEX idx_room_images_room_id ON room_images');
        $this->addSql('CREATE INDEX IDX_A15178AB54177093 ON room_images (room_id)');
        $this->addSql('ALTER TABLE room_images ADD CONSTRAINT fk_room_images_room FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE saved_posts DROP FOREIGN KEY fk_saved_post');
        $this->addSql('ALTER TABLE saved_posts DROP FOREIGN KEY fk_saved_user');
        $this->addSql('DROP INDEX idx_saved_user ON saved_posts');
        $this->addSql('DROP INDEX idx_saved_post ON saved_posts');
        $this->addSql('DROP INDEX unique_save ON saved_posts');
        $this->addSql('ALTER TABLE saved_posts CHANGE saved_at saved_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE schedule DROP FOREIGN KEY fk_schedule_arrival');
        $this->addSql('ALTER TABLE schedule DROP FOREIGN KEY fk_schedule_departure');
        $this->addSql('ALTER TABLE schedule DROP FOREIGN KEY fk_schedule_transport');
        $this->addSql('DROP INDEX fk_schedule_arrival ON schedule');
        $this->addSql('DROP INDEX fk_schedule_transport ON schedule');
        $this->addSql('DROP INDEX fk_schedule_departure ON schedule');
        $this->addSql('ALTER TABLE schedule CHANGE departure_destination_id departure_destination_id BIGINT NOT NULL, CHANGE arrival_destination_id arrival_destination_id BIGINT NOT NULL, CHANGE price_multiplier price_multiplier DOUBLE PRECISION NOT NULL, CHANGE status status VARCHAR(255) DEFAULT \'ON_TIME\' NOT NULL, CHANGE delay_minutes delay_minutes INT NOT NULL, CHANGE ai_demand_score ai_demand_score DOUBLE PRECISION NOT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE shares DROP FOREIGN KEY shares_ibfk_1');
        $this->addSql('ALTER TABLE shares DROP FOREIGN KEY shares_ibfk_2');
        $this->addSql('ALTER TABLE shares DROP FOREIGN KEY shares_ibfk_3');
        $this->addSql('DROP INDEX idx_shares_user ON shares');
        $this->addSql('DROP INDEX idx_shares_post ON shares');
        $this->addSql('DROP INDEX idx_shares_story ON shares');
        $this->addSql('ALTER TABLE shares CHANGE created_at created_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE stories DROP FOREIGN KEY stories_ibfk_1');
        $this->addSql('DROP INDEX idx_stories_exp ON stories');
        $this->addSql('DROP INDEX idx_stories_user ON stories');
        $this->addSql('ALTER TABLE stories CHANGE created_at created_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE transport CHANGE provider_name provider_name VARCHAR(255) NOT NULL, CHANGE vehicle_model vehicle_model VARCHAR(255) NOT NULL, CHANGE base_price base_price DOUBLE PRECISION NOT NULL, CHANGE capacity capacity INT NOT NULL, CHANGE available_units available_units INT NOT NULL, CHANGE sustainability_rating sustainability_rating DOUBLE PRECISION NOT NULL, CHANGE amenities amenities VARCHAR(255) DEFAULT NULL, CHANGE dynamic_price_factor dynamic_price_factor DOUBLE PRECISION NOT NULL, CHANGE is_active is_active TINYINT(1) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE travel_story DROP FOREIGN KEY travel_story_ibfk_1');
        $this->addSql('DROP INDEX user_id ON travel_story');
        $this->addSql('ALTER TABLE travel_story CHANGE destination_id destination_id BIGINT DEFAULT NULL, CHANGE summary summary LONGTEXT DEFAULT NULL, CHANGE overall_rating overall_rating SMALLINT UNSIGNED DEFAULT NULL, CHANGE tips tips LONGTEXT DEFAULT NULL, CHANGE budget_json budget_json JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE tags_json tags_json JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE must_visit_json must_visit_json JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE must_do_json must_do_json JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE must_try_json must_try_json JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE favorite_places_json favorite_places_json JSON DEFAULT NULL COMMENT \'(DC2Type:json)\', CHANGE image_urls_json image_urls_json JSON DEFAULT NULL COMMENT \'(DC2Type:json)\'');
        $this->addSql('ALTER TABLE user ADD login_attempts INT DEFAULT 0 NOT NULL, ADD last_login_attempt DATETIME DEFAULT NULL, ADD locked_until DATETIME DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE community_statistics (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, posts_count INT DEFAULT 0, comments_count INT DEFAULT 0, reactions_count INT DEFAULT 0, badges_count INT DEFAULT 0, followers_count INT DEFAULT 0, other_stats VARCHAR(1000) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_general_ci`, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, UNIQUE INDEX unique_user_stats (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE reports (id INT AUTO_INCREMENT NOT NULL, reported_by_id INT NOT NULL, reported_user_id INT DEFAULT NULL, reported_post_id INT DEFAULT NULL, reported_comment_id INT DEFAULT NULL, report_type VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, reason VARCHAR(1000) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_general_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, status VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT \'pending\' COLLATE `utf8mb4_general_ci`, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_general_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE community_statistics ADD CONSTRAINT fk_stats_user FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE accommodation CHANGE description description TEXT DEFAULT NULL, CHANGE accommodation_amenities accommodation_amenities TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE activities DROP FOREIGN KEY FK_B5F1AFE5816C6140');
        $this->addSql('ALTER TABLE activities DROP FOREIGN KEY FK_B5F1AFE5816C6140');
        $this->addSql('ALTER TABLE activities CHANGE activity_id activity_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE destination_id destination_id BIGINT UNSIGNED NOT NULL, CHANGE category category VARCHAR(255) NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE duration_minutes duration_minutes SMALLINT UNSIGNED DEFAULT NULL, CHANGE currency currency CHAR(3) DEFAULT \'USD\' NOT NULL, CHANGE age_min age_min TINYINT(1) DEFAULT NULL, CHANGE capacity capacity SMALLINT UNSIGNED DEFAULT NULL');
        $this->addSql('ALTER TABLE activities ADD CONSTRAINT activities_ibfk_1 FOREIGN KEY (destination_id) REFERENCES destinations (destination_id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_b5f1afe5816c6140 ON activities');
        $this->addSql('CREATE INDEX destination_id ON activities (destination_id)');
        $this->addSql('ALTER TABLE activities ADD CONSTRAINT FK_B5F1AFE5816C6140 FOREIGN KEY (destination_id) REFERENCES destinations (destination_id)');
        $this->addSql('ALTER TABLE bookingacc DROP FOREIGN KEY FK_494EA9D354177093');
        $this->addSql('ALTER TABLE bookingacc CHANGE special_requests special_requests TEXT DEFAULT NULL, CHANGE cancel_reason cancel_reason TEXT DEFAULT NULL, CHANGE rejection_reason rejection_reason TEXT DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT \'PENDING\', CHANGE calendar_sync_status calendar_sync_status VARCHAR(255) DEFAULT \'NOT_SYNCED\' NOT NULL, CHANGE calendar_last_error calendar_last_error TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE bookingacc ADD CONSTRAINT fk_bookingacc_user FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bookingacc ADD CONSTRAINT fk_bookingacc_room FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX idx_bookingacc_status_created ON bookingacc (status, created_at)');
        $this->addSql('CREATE INDEX idx_bookingacc_room_status_dates ON bookingacc (room_id, status, check_in, check_out)');
        $this->addSql('CREATE INDEX idx_bookingacc_user_created ON bookingacc (user_id, created_at)');
        $this->addSql('CREATE INDEX IDX_494EA9D3A76ED395 ON bookingacc (user_id)');
        $this->addSql('ALTER TABLE bookingdes CHANGE booking_id booking_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE destination_id destination_id BIGINT UNSIGNED DEFAULT NULL, CHANGE activity_id activity_id BIGINT UNSIGNED DEFAULT NULL, CHANGE num_guests num_guests SMALLINT UNSIGNED DEFAULT 1 NOT NULL, CHANGE status status VARCHAR(255) DEFAULT \'pending\' NOT NULL, CHANGE payment_status payment_status VARCHAR(255) DEFAULT \'unpaid\' NOT NULL, CHANGE currency currency CHAR(3) DEFAULT \'USD\' NOT NULL, CHANGE notes notes TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE bookingdes ADD CONSTRAINT bookingdes_ibfk_3 FOREIGN KEY (activity_id) REFERENCES activities (activity_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bookingdes ADD CONSTRAINT bookingdes_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bookingdes ADD CONSTRAINT bookingdes_ibfk_2 FOREIGN KEY (destination_id) REFERENCES destinations (destination_id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX activity_id ON bookingdes (activity_id)');
        $this->addSql('CREATE INDEX user_id ON bookingdes (user_id)');
        $this->addSql('CREATE INDEX destination_id ON bookingdes (destination_id)');
        $this->addSql('ALTER TABLE bookingtrans CHANGE booking_date booking_date DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE adults_count adults_count INT DEFAULT 0, CHANGE children_count children_count INT DEFAULT 0, CHANGE total_price total_price NUMERIC(10, 2) NOT NULL, CHANGE booking_status booking_status VARCHAR(255) DEFAULT \'PENDING\', CHANGE payment_status payment_status VARCHAR(255) DEFAULT \'UNPAID\', CHANGE insurance_included insurance_included TINYINT(1) DEFAULT 0, CHANGE ai_price_prediction ai_price_prediction DOUBLE PRECISION DEFAULT NULL, CHANGE comparison_score comparison_score DOUBLE PRECISION DEFAULT NULL, CHANGE cancellation_reason cancellation_reason TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE bookingtrans ADD CONSTRAINT bookingtrans_ibfk_3 FOREIGN KEY (schedule_id) REFERENCES schedule (schedule_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bookingtrans ADD CONSTRAINT bookingtrans_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bookingtrans ADD CONSTRAINT bookingtrans_ibfk_2 FOREIGN KEY (transport_id) REFERENCES transport (transport_id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX transport_id ON bookingtrans (transport_id)');
        $this->addSql('CREATE INDEX schedule_id ON bookingtrans (schedule_id)');
        $this->addSql('CREATE INDEX user_id ON bookingtrans (user_id)');
        $this->addSql('ALTER TABLE comments DROP FOREIGN KEY FK_5F9E962A4B89032C');
        $this->addSql('DROP INDEX IDX_5F9E962A4B89032C ON comments');
        $this->addSql('ALTER TABLE comments CHANGE body body TEXT NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE comments ADD CONSTRAINT comments_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX comments_ibfk_1 ON comments (user_id)');
        $this->addSql('ALTER TABLE destinations CHANGE destination_id destination_id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE type type VARCHAR(255) NOT NULL, CHANGE best_season best_season VARCHAR(255) NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE popularity popularity INT DEFAULT 0');
        $this->addSql('ALTER TABLE destination_trans ADD created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, CHANGE name name VARCHAR(150) NOT NULL, CHANGE type type VARCHAR(255) NOT NULL, CHANGE city city VARCHAR(100) DEFAULT NULL, CHANGE best_season best_season VARCHAR(255) NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE average_rating average_rating NUMERIC(3, 2) DEFAULT \'0.00\' NOT NULL');
        $this->addSql('ALTER TABLE followings CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE followings ADD CONSTRAINT followings_ibfk_1 FOREIGN KEY (follower_id) REFERENCES user (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE followings ADD CONSTRAINT followings_ibfk_2 FOREIGN KEY (followed_id) REFERENCES user (user_id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX followings_ibfk_2 ON followings (followed_id)');
        $this->addSql('CREATE INDEX followings_ibfk_1 ON followings (follower_id)');
        $this->addSql('ALTER TABLE loyalty_points CHANGE user_id user_id INT DEFAULT NULL, CHANGE total_points total_points INT DEFAULT 0, CHANGE level level VARCHAR(255) DEFAULT \'BRONZE\'');
        $this->addSql('ALTER TABLE loyalty_points ADD CONSTRAINT loyalty_points_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE');
        $this->addSql('CREATE UNIQUE INDEX user_id ON loyalty_points (user_id)');
        $this->addSql('ALTER TABLE offers CHANGE title title VARCHAR(150) NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE discount_type discount_type VARCHAR(255) NOT NULL, CHANGE discount_value discount_value NUMERIC(5, 2) NOT NULL, CHANGE destination_id destination_id BIGINT UNSIGNED DEFAULT NULL, CHANGE start_date start_date DATE DEFAULT NULL, CHANGE end_date end_date DATE DEFAULT NULL, CHANGE is_active is_active TINYINT(1) DEFAULT 1');
        $this->addSql('ALTER TABLE offers ADD CONSTRAINT offers_ibfk_1 FOREIGN KEY (pack_id) REFERENCES packs (id_pack) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE offers ADD CONSTRAINT offers_ibfk_2 FOREIGN KEY (destination_id) REFERENCES destinations (destination_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE offers ADD CONSTRAINT offers_ibfk_3 FOREIGN KEY (accommodation_id) REFERENCES accommodation (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX accommodation_id ON offers (accommodation_id)');
        $this->addSql('CREATE INDEX pack_id ON offers (pack_id)');
        $this->addSql('CREATE INDEX destination_id ON offers (destination_id)');
        $this->addSql('ALTER TABLE packs CHANGE title title VARCHAR(150) NOT NULL, CHANGE description description TEXT DEFAULT NULL, CHANGE destination_id destination_id BIGINT UNSIGNED DEFAULT NULL, CHANGE activity_id activity_id BIGINT UNSIGNED DEFAULT NULL, CHANGE duration_days duration_days INT DEFAULT NULL, CHANGE base_price base_price NUMERIC(10, 2) DEFAULT NULL, CHANGE status status VARCHAR(255) DEFAULT \'ACTIVE\'');
        $this->addSql('ALTER TABLE packs ADD CONSTRAINT packs_ibfk_1 FOREIGN KEY (destination_id) REFERENCES destinations (destination_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE packs ADD CONSTRAINT packs_ibfk_4 FOREIGN KEY (transport_id) REFERENCES transport (transport_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE packs ADD CONSTRAINT packs_ibfk_2 FOREIGN KEY (accommodation_id) REFERENCES accommodation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE packs ADD CONSTRAINT packs_ibfk_5 FOREIGN KEY (category_id) REFERENCES pack_categories (id_category) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE packs ADD CONSTRAINT packs_ibfk_3 FOREIGN KEY (activity_id) REFERENCES activities (activity_id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX accommodation_id ON packs (accommodation_id)');
        $this->addSql('CREATE INDEX activity_id ON packs (activity_id)');
        $this->addSql('CREATE INDEX transport_id ON packs (transport_id)');
        $this->addSql('CREATE INDEX destination_id ON packs (destination_id)');
        $this->addSql('CREATE INDEX category_id ON packs (category_id)');
        $this->addSql('ALTER TABLE packs_bookings CHANGE num_travelers num_travelers INT DEFAULT 1, CHANGE discount_applied discount_applied NUMERIC(5, 2) DEFAULT \'0.00\', CHANGE status status VARCHAR(255) DEFAULT \'PENDING\', CHANGE notes notes TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE packs_bookings ADD CONSTRAINT packs_bookings_ibfk_2 FOREIGN KEY (pack_id) REFERENCES packs (id_pack) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE packs_bookings ADD CONSTRAINT packs_bookings_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX idx_booking_date ON packs_bookings (booking_date)');
        $this->addSql('CREATE INDEX idx_status ON packs_bookings (status)');
        $this->addSql('CREATE INDEX idx_user_id ON packs_bookings (user_id)');
        $this->addSql('CREATE INDEX idx_pack_id ON packs_bookings (pack_id)');
        $this->addSql('ALTER TABLE posts CHANGE body body TEXT NOT NULL, CHANGE type type VARCHAR(255) NOT NULL, CHANGE image_url image_url VARCHAR(500) DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE is_confirmed is_confirmed TINYINT(1) DEFAULT 0');
        $this->addSql('ALTER TABLE posts ADD CONSTRAINT posts_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX posts_ibfk_1 ON posts (user_id)');
        $this->addSql('ALTER TABLE price_alerts CHANGE activity_id activity_id BIGINT UNSIGNED NOT NULL, CHANGE direction direction VARCHAR(255) NOT NULL, CHANGE is_active is_active TINYINT(1) DEFAULT 1, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE price_alerts ADD CONSTRAINT price_alerts_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (user_id)');
        $this->addSql('ALTER TABLE price_alerts ADD CONSTRAINT price_alerts_ibfk_2 FOREIGN KEY (activity_id) REFERENCES activities (activity_id)');
        $this->addSql('CREATE INDEX user_id ON price_alerts (user_id)');
        $this->addSql('CREATE INDEX activity_id ON price_alerts (activity_id)');
        $this->addSql('ALTER TABLE reactions CHANGE type type VARCHAR(255) NOT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE reactions ADD CONSTRAINT fk_reactions_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reactions ADD CONSTRAINT fk_reactions_story FOREIGN KEY (travel_story_id) REFERENCES travel_story (travel_story_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE reactions ADD CONSTRAINT fk_reactions_comment FOREIGN KEY (comment_id) REFERENCES comments (id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX fk_reactions_story ON reactions (travel_story_id)');
        $this->addSql('CREATE INDEX idx_reactions_post ON reactions (post_id)');
        $this->addSql('CREATE INDEX idx_reactions_comment ON reactions (comment_id)');
        $this->addSql('ALTER TABLE room DROP FOREIGN KEY FK_729F519B8F3692CD');
        $this->addSql('ALTER TABLE room DROP FOREIGN KEY FK_729F519B8F3692CD');
        $this->addSql('ALTER TABLE room CHANGE amenities amenities TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT room_ibfk_1 FOREIGN KEY (accommodation_id) REFERENCES accommodation (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_729f519b8f3692cd ON room');
        $this->addSql('CREATE INDEX accommodation_id ON room (accommodation_id)');
        $this->addSql('ALTER TABLE room ADD CONSTRAINT FK_729F519B8F3692CD FOREIGN KEY (accommodation_id) REFERENCES accommodation (id)');
        $this->addSql('ALTER TABLE room_images DROP FOREIGN KEY FK_A15178AB54177093');
        $this->addSql('ALTER TABLE room_images DROP FOREIGN KEY FK_A15178AB54177093');
        $this->addSql('ALTER TABLE room_images ADD CONSTRAINT fk_room_images_room FOREIGN KEY (room_id) REFERENCES room (id) ON DELETE CASCADE');
        $this->addSql('DROP INDEX idx_a15178ab54177093 ON room_images');
        $this->addSql('CREATE INDEX idx_room_images_room_id ON room_images (room_id)');
        $this->addSql('ALTER TABLE room_images ADD CONSTRAINT FK_A15178AB54177093 FOREIGN KEY (room_id) REFERENCES room (id)');
        $this->addSql('ALTER TABLE saved_posts CHANGE saved_at saved_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE saved_posts ADD CONSTRAINT fk_saved_post FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE saved_posts ADD CONSTRAINT fk_saved_user FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX idx_saved_user ON saved_posts (user_id)');
        $this->addSql('CREATE INDEX idx_saved_post ON saved_posts (post_id)');
        $this->addSql('CREATE UNIQUE INDEX unique_save ON saved_posts (user_id, post_id)');
        $this->addSql('ALTER TABLE schedule CHANGE departure_destination_id departure_destination_id INT NOT NULL, CHANGE arrival_destination_id arrival_destination_id INT NOT NULL, CHANGE price_multiplier price_multiplier DOUBLE PRECISION DEFAULT \'1\', CHANGE status status VARCHAR(255) DEFAULT \'ON_TIME\', CHANGE delay_minutes delay_minutes INT DEFAULT 0, CHANGE ai_demand_score ai_demand_score DOUBLE PRECISION DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT fk_schedule_arrival FOREIGN KEY (arrival_destination_id) REFERENCES destination_trans (destination_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT fk_schedule_departure FOREIGN KEY (departure_destination_id) REFERENCES destination_trans (destination_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE schedule ADD CONSTRAINT fk_schedule_transport FOREIGN KEY (transport_id) REFERENCES transport (transport_id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX fk_schedule_arrival ON schedule (arrival_destination_id)');
        $this->addSql('CREATE INDEX fk_schedule_transport ON schedule (transport_id)');
        $this->addSql('CREATE INDEX fk_schedule_departure ON schedule (departure_destination_id)');
        $this->addSql('ALTER TABLE shares CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE shares ADD CONSTRAINT shares_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE shares ADD CONSTRAINT shares_ibfk_2 FOREIGN KEY (post_id) REFERENCES posts (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE shares ADD CONSTRAINT shares_ibfk_3 FOREIGN KEY (travel_story_id) REFERENCES travel_story (travel_story_id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX idx_shares_user ON shares (user_id)');
        $this->addSql('CREATE INDEX idx_shares_post ON shares (post_id)');
        $this->addSql('CREATE INDEX idx_shares_story ON shares (travel_story_id)');
        $this->addSql('ALTER TABLE stories CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL');
        $this->addSql('ALTER TABLE stories ADD CONSTRAINT stories_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX idx_stories_exp ON stories (expires_at)');
        $this->addSql('CREATE INDEX idx_stories_user ON stories (user_id)');
        $this->addSql('ALTER TABLE transport CHANGE provider_name provider_name VARCHAR(100) DEFAULT NULL, CHANGE vehicle_model vehicle_model VARCHAR(100) DEFAULT NULL, CHANGE base_price base_price NUMERIC(10, 2) DEFAULT NULL, CHANGE capacity capacity INT DEFAULT NULL, CHANGE available_units available_units INT DEFAULT NULL, CHANGE sustainability_rating sustainability_rating DOUBLE PRECISION DEFAULT NULL, CHANGE amenities amenities TEXT DEFAULT NULL, CHANGE dynamic_price_factor dynamic_price_factor DOUBLE PRECISION DEFAULT \'1\', CHANGE is_active is_active TINYINT(1) DEFAULT 1, CHANGE created_at created_at DATETIME DEFAULT CURRENT_TIMESTAMP, CHANGE updated_at updated_at DATETIME DEFAULT CURRENT_TIMESTAMP');
        $this->addSql('ALTER TABLE travel_story CHANGE destination_id destination_id BIGINT UNSIGNED DEFAULT NULL, CHANGE summary summary TEXT DEFAULT NULL, CHANGE overall_rating overall_rating TINYINT(1) DEFAULT NULL, CHANGE tips tips TEXT DEFAULT NULL, CHANGE budget_json budget_json LONGTEXT DEFAULT NULL, CHANGE tags_json tags_json LONGTEXT DEFAULT NULL, CHANGE must_visit_json must_visit_json LONGTEXT DEFAULT NULL, CHANGE must_do_json must_do_json LONGTEXT DEFAULT NULL, CHANGE must_try_json must_try_json LONGTEXT DEFAULT NULL, CHANGE favorite_places_json favorite_places_json LONGTEXT DEFAULT NULL, CHANGE image_urls_json image_urls_json LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE travel_story ADD CONSTRAINT travel_story_ibfk_1 FOREIGN KEY (user_id) REFERENCES user (user_id) ON DELETE CASCADE');
        $this->addSql('CREATE INDEX user_id ON travel_story (user_id)');
        $this->addSql('ALTER TABLE user DROP login_attempts, DROP last_login_attempt, DROP locked_until');
    }
}
