security:

  password_hashers:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class:    App\Entity\User
        property: email

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      lazy: true
      provider: app_user_provider

      form_login:
        login_path:     app_login
        check_path:     app_login
        username_parameter: _username
        password_parameter: _password
        success_handler: App\Security\LoginSuccessHandler
        enable_csrf: true
        csrf_token_id: authenticate

      logout:
        path:         app_logout
        target:       app_login

  access_control:
    - { path: ^/$,           roles: PUBLIC_ACCESS }
    - { path: ^/register,    roles: PUBLIC_ACCESS }
    - { path: ^/onboarding,  roles: PUBLIC_ACCESS }
    - { path: ^/preferences, roles: PUBLIC_ACCESS }
    - { path: ^/images,      roles: PUBLIC_ACCESS }
    - { path: ^/css,         roles: PUBLIC_ACCESS }
    - { path: ^/js,          roles: PUBLIC_ACCESS }
    - { path: ^/admin,       roles: [ROLE_ADMIN, ROLE_ADMIN_DESTINATION, ROLE_ADMIN_ACCOMODATION, ROLE_ADMIN_OFFERS, ROLE_ADMIN_BLOG, ROLE_ADMIN_TRANSPORT] }
    - { path: ^/,            roles: ROLE_USER }
