<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Activity extends \App\Entity\Activity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'activityId', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'destinationId', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'category', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'durationMinutes', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'currency', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'ageMin', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'capacity', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'availableFrom', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'availableTo', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'meetingPoint', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'averageRating', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'isActive', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'createdAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'activityId', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'destinationId', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'category', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'durationMinutes', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'price', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'currency', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'ageMin', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'capacity', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'availableFrom', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'availableTo', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'meetingPoint', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'averageRating', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'isActive', '' . "\0" . 'App\\Entity\\Activity' . "\0" . 'createdAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Activity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getActivityId(): ?string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getActivityId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActivityId', []);

        return parent::getActivityId();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDestinationId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestinationId', []);

        return parent::getDestinationId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestinationId(string $destinationId): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestinationId', [$destinationId]);

        return parent::setDestinationId($destinationId);
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(string $name): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategory(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategory', []);

        return parent::getCategory();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategory(string $category): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategory', [$category]);

        return parent::setCategory($category);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDurationMinutes(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDurationMinutes', []);

        return parent::getDurationMinutes();
    }

    /**
     * {@inheritDoc}
     */
    public function setDurationMinutes(?int $durationMinutes): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDurationMinutes', [$durationMinutes]);

        return parent::setDurationMinutes($durationMinutes);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrice(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrice', []);

        return parent::getPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrice(?string $price): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrice', [$price]);

        return parent::setPrice($price);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', []);

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency(string $currency): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', [$currency]);

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgeMin(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgeMin', []);

        return parent::getAgeMin();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgeMin(?int $ageMin): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgeMin', [$ageMin]);

        return parent::setAgeMin($ageMin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCapacity(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCapacity', []);

        return parent::getCapacity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCapacity(?int $capacity): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCapacity', [$capacity]);

        return parent::setCapacity($capacity);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailableFrom(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailableFrom', []);

        return parent::getAvailableFrom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailableFrom(?\DateTimeInterface $availableFrom): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailableFrom', [$availableFrom]);

        return parent::setAvailableFrom($availableFrom);
    }

    /**
     * {@inheritDoc}
     */
    public function getAvailableTo(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAvailableTo', []);

        return parent::getAvailableTo();
    }

    /**
     * {@inheritDoc}
     */
    public function setAvailableTo(?\DateTimeInterface $availableTo): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAvailableTo', [$availableTo]);

        return parent::setAvailableTo($availableTo);
    }

    /**
     * {@inheritDoc}
     */
    public function getMeetingPoint(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMeetingPoint', []);

        return parent::getMeetingPoint();
    }

    /**
     * {@inheritDoc}
     */
    public function setMeetingPoint(?string $meetingPoint): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMeetingPoint', [$meetingPoint]);

        return parent::setMeetingPoint($meetingPoint);
    }

    /**
     * {@inheritDoc}
     */
    public function getAverageRating(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAverageRating', []);

        return parent::getAverageRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setAverageRating(string $averageRating): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAverageRating', [$averageRating]);

        return parent::setAverageRating($averageRating);
    }

    /**
     * {@inheritDoc}
     */
    public function isIsActive(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isIsActive', []);

        return parent::isIsActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setIsActive(bool $isActive): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIsActive', [$isActive]);

        return parent::setIsActive($isActive);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

}
