<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Preference extends \App\Entity\Preference implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'preferenceId', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'userId', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'budgetMinPerNight', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'budgetMaxPerNight', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'priorities', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'locationPreferences', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'accommodationTypes', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'stylePreferences', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'dietaryRestrictions', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'preferredClimate', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'travelPace', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'groupType', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'accessibilityNeeds', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'preferenceId', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'userId', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'budgetMinPerNight', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'budgetMaxPerNight', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'priorities', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'locationPreferences', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'accommodationTypes', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'stylePreferences', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'dietaryRestrictions', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'preferredClimate', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'travelPace', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'groupType', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'accessibilityNeeds', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Preference' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Preference $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getPreferenceId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getPreferenceId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferenceId', []);

        return parent::getPreferenceId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId(int $userId): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$userId]);

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getBudgetMinPerNight(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBudgetMinPerNight', []);

        return parent::getBudgetMinPerNight();
    }

    /**
     * {@inheritDoc}
     */
    public function setBudgetMinPerNight(?float $v): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBudgetMinPerNight', [$v]);

        return parent::setBudgetMinPerNight($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getBudgetMaxPerNight(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBudgetMaxPerNight', []);

        return parent::getBudgetMaxPerNight();
    }

    /**
     * {@inheritDoc}
     */
    public function setBudgetMaxPerNight(?float $v): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBudgetMaxPerNight', [$v]);

        return parent::setBudgetMaxPerNight($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getPriorities(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPriorities', []);

        return parent::getPriorities();
    }

    /**
     * {@inheritDoc}
     */
    public function setPriorities(?string $v): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPriorities', [$v]);

        return parent::setPriorities($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocationPreferences(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocationPreferences', []);

        return parent::getLocationPreferences();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocationPreferences(?string $v): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocationPreferences', [$v]);

        return parent::setLocationPreferences($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccommodationTypes(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccommodationTypes', []);

        return parent::getAccommodationTypes();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccommodationTypes(?string $v): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccommodationTypes', [$v]);

        return parent::setAccommodationTypes($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getStylePreferences(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStylePreferences', []);

        return parent::getStylePreferences();
    }

    /**
     * {@inheritDoc}
     */
    public function setStylePreferences(?string $v): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStylePreferences', [$v]);

        return parent::setStylePreferences($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getDietaryRestrictions(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDietaryRestrictions', []);

        return parent::getDietaryRestrictions();
    }

    /**
     * {@inheritDoc}
     */
    public function setDietaryRestrictions(?string $v): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDietaryRestrictions', [$v]);

        return parent::setDietaryRestrictions($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getPreferredClimate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPreferredClimate', []);

        return parent::getPreferredClimate();
    }

    /**
     * {@inheritDoc}
     */
    public function setPreferredClimate(?string $v): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPreferredClimate', [$v]);

        return parent::setPreferredClimate($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getTravelPace(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTravelPace', []);

        return parent::getTravelPace();
    }

    /**
     * {@inheritDoc}
     */
    public function setTravelPace(?string $v): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTravelPace', [$v]);

        return parent::setTravelPace($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getGroupType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGroupType', []);

        return parent::getGroupType();
    }

    /**
     * {@inheritDoc}
     */
    public function setGroupType(?string $v): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGroupType', [$v]);

        return parent::setGroupType($v);
    }

    /**
     * {@inheritDoc}
     */
    public function getAccessibilityNeeds(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAccessibilityNeeds', []);

        return parent::getAccessibilityNeeds();
    }

    /**
     * {@inheritDoc}
     */
    public function setAccessibilityNeeds(?bool $v): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAccessibilityNeeds', [$v]);

        return parent::setAccessibilityNeeds($v);
    }

}
