<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TravelStory extends \App\Entity\TravelStory implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'userId', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'destinationId', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'title', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'summary', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'startDate', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'endDate', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'travelType', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'travelStyle', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'overallRating', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'wouldRecommend', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'wouldGoAgain', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'tips', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'currency', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'totalBudget', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'budgetJson', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'tagsJson', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'mustVisitJson', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'mustDoJson', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'mustTryJson', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'favoritePlacesJson', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'destination', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'coverImageUrl', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'imageUrlsJson', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'updatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'userId', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'destinationId', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'title', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'summary', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'startDate', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'endDate', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'travelType', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'travelStyle', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'overallRating', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'wouldRecommend', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'wouldGoAgain', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'tips', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'currency', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'totalBudget', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'budgetJson', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'tagsJson', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'mustVisitJson', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'mustDoJson', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'mustTryJson', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'favoritePlacesJson', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'destination', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'coverImageUrl', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'imageUrlsJson', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\TravelStory' . "\0" . 'updatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TravelStory $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserId(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId(int $userId): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$userId]);

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestinationId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestinationId', []);

        return parent::getDestinationId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestinationId(?string $destinationId): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestinationId', [$destinationId]);

        return parent::setDestinationId($destinationId);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $title): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getSummary(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSummary', []);

        return parent::getSummary();
    }

    /**
     * {@inheritDoc}
     */
    public function setSummary(?string $summary): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSummary', [$summary]);

        return parent::setSummary($summary);
    }

    /**
     * {@inheritDoc}
     */
    public function getStartDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStartDate', []);

        return parent::getStartDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setStartDate(?\DateTimeInterface $startDate): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStartDate', [$startDate]);

        return parent::setStartDate($startDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndDate', []);

        return parent::getEndDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndDate(?\DateTimeInterface $endDate): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndDate', [$endDate]);

        return parent::setEndDate($endDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getTravelType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTravelType', []);

        return parent::getTravelType();
    }

    /**
     * {@inheritDoc}
     */
    public function setTravelType(?string $travelType): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTravelType', [$travelType]);

        return parent::setTravelType($travelType);
    }

    /**
     * {@inheritDoc}
     */
    public function getTravelStyle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTravelStyle', []);

        return parent::getTravelStyle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTravelStyle(?string $travelStyle): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTravelStyle', [$travelStyle]);

        return parent::setTravelStyle($travelStyle);
    }

    /**
     * {@inheritDoc}
     */
    public function getOverallRating(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOverallRating', []);

        return parent::getOverallRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setOverallRating(?int $overallRating): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOverallRating', [$overallRating]);

        return parent::setOverallRating($overallRating);
    }

    /**
     * {@inheritDoc}
     */
    public function isWouldRecommend(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isWouldRecommend', []);

        return parent::isWouldRecommend();
    }

    /**
     * {@inheritDoc}
     */
    public function setWouldRecommend(bool $wouldRecommend): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWouldRecommend', [$wouldRecommend]);

        return parent::setWouldRecommend($wouldRecommend);
    }

    /**
     * {@inheritDoc}
     */
    public function isWouldGoAgain(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isWouldGoAgain', []);

        return parent::isWouldGoAgain();
    }

    /**
     * {@inheritDoc}
     */
    public function setWouldGoAgain(bool $wouldGoAgain): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWouldGoAgain', [$wouldGoAgain]);

        return parent::setWouldGoAgain($wouldGoAgain);
    }

    /**
     * {@inheritDoc}
     */
    public function getTips(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTips', []);

        return parent::getTips();
    }

    /**
     * {@inheritDoc}
     */
    public function setTips(?string $tips): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTips', [$tips]);

        return parent::setTips($tips);
    }

    /**
     * {@inheritDoc}
     */
    public function getCurrency(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCurrency', []);

        return parent::getCurrency();
    }

    /**
     * {@inheritDoc}
     */
    public function setCurrency(string $currency): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCurrency', [$currency]);

        return parent::setCurrency($currency);
    }

    /**
     * {@inheritDoc}
     */
    public function getTotalBudget(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTotalBudget', []);

        return parent::getTotalBudget();
    }

    /**
     * {@inheritDoc}
     */
    public function setTotalBudget(?string $totalBudget): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTotalBudget', [$totalBudget]);

        return parent::setTotalBudget($totalBudget);
    }

    /**
     * {@inheritDoc}
     */
    public function getBudgetJson(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBudgetJson', []);

        return parent::getBudgetJson();
    }

    /**
     * {@inheritDoc}
     */
    public function setBudgetJson(?array $budgetJson): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBudgetJson', [$budgetJson]);

        return parent::setBudgetJson($budgetJson);
    }

    /**
     * {@inheritDoc}
     */
    public function getTagsJson(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTagsJson', []);

        return parent::getTagsJson();
    }

    /**
     * {@inheritDoc}
     */
    public function setTagsJson(?array $tagsJson): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTagsJson', [$tagsJson]);

        return parent::setTagsJson($tagsJson);
    }

    /**
     * {@inheritDoc}
     */
    public function getMustVisitJson(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMustVisitJson', []);

        return parent::getMustVisitJson();
    }

    /**
     * {@inheritDoc}
     */
    public function setMustVisitJson(?array $mustVisitJson): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMustVisitJson', [$mustVisitJson]);

        return parent::setMustVisitJson($mustVisitJson);
    }

    /**
     * {@inheritDoc}
     */
    public function getMustDoJson(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMustDoJson', []);

        return parent::getMustDoJson();
    }

    /**
     * {@inheritDoc}
     */
    public function setMustDoJson(?array $mustDoJson): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMustDoJson', [$mustDoJson]);

        return parent::setMustDoJson($mustDoJson);
    }

    /**
     * {@inheritDoc}
     */
    public function getMustTryJson(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMustTryJson', []);

        return parent::getMustTryJson();
    }

    /**
     * {@inheritDoc}
     */
    public function setMustTryJson(?array $mustTryJson): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMustTryJson', [$mustTryJson]);

        return parent::setMustTryJson($mustTryJson);
    }

    /**
     * {@inheritDoc}
     */
    public function getFavoritePlacesJson(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFavoritePlacesJson', []);

        return parent::getFavoritePlacesJson();
    }

    /**
     * {@inheritDoc}
     */
    public function setFavoritePlacesJson(?array $favoritePlacesJson): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFavoritePlacesJson', [$favoritePlacesJson]);

        return parent::setFavoritePlacesJson($favoritePlacesJson);
    }

    /**
     * {@inheritDoc}
     */
    public function getDestination(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestination', []);

        return parent::getDestination();
    }

    /**
     * {@inheritDoc}
     */
    public function setDestination(?string $destination): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDestination', [$destination]);

        return parent::setDestination($destination);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoverImageUrl(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoverImageUrl', []);

        return parent::getCoverImageUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoverImageUrl(?string $coverImageUrl): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoverImageUrl', [$coverImageUrl]);

        return parent::setCoverImageUrl($coverImageUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageUrlsJson(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageUrlsJson', []);

        return parent::getImageUrlsJson();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageUrlsJson(?array $imageUrlsJson): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageUrlsJson', [$imageUrlsJson]);

        return parent::setImageUrlsJson($imageUrlsJson);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdatedAt', []);

        return parent::getUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdatedAt(?\DateTimeInterface $updatedAt): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdatedAt', [$updatedAt]);

        return parent::setUpdatedAt($updatedAt);
    }

}
