<?php

namespace ContainerOfKhxAt;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\user\UserController' shared autowired service.
     *
     * @return \App\Controller\user\UserController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\user\\UserController'] = $instance = new \App\Controller\user\UserController(($container->privates['App\\service\\UserProfileService'] ?? $container->load('getUserProfileServiceService')), ($container->privates['App\\service\\PreferenceService'] ?? $container->load('getPreferenceServiceService')), ($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\user\\UserController', $container));

        return $instance;
    }
}
