<?php

namespace ContainerTjRJaqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_AszDvkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored._AszDvk' shared service.
     *
     * @return \App\Controller\user\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\user\\ChatController::chat()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\user\\Request". Did you forget to add a use statement?');
    }
}
