<?php

namespace ContainerTjRJaqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGeminiServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\service\GeminiService' shared autowired service.
     *
     * @return \App\service\GeminiService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\service\\GeminiService'] = new \App\service\GeminiService(($container->privates['http_client.uri_template'] ?? $container->load('getHttpClient_UriTemplateService')), $container->getEnv('GEMINI_API_KEY'), $container->getEnv('GEMINI_MODEL'));
    }
}
