<?php

namespace ContainerTjRJaqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\form\RegistrationFormType' shared autowired service.
     *
     * @return \App\form\RegistrationFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\form\\RegistrationFormType'] = new \App\form\RegistrationFormType();
    }
}
