<?php

namespace ContainerTjRJaqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestDatabaseCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\TestDatabaseCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\TestDatabaseCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('TestDatabaseCommand', [], 'Add a short description for your command', false, #[\Closure(name: 'App\\Command\\TestDatabaseCommand')] fn (): \App\Command\TestDatabaseCommand => ($container->privates['App\\Command\\TestDatabaseCommand'] ?? $container->load('getTestDatabaseCommandService')));
    }
}
