<?php

namespace ContainerTjRJaqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestDatabaseCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TestDatabaseCommand' shared autowired service.
     *
     * @return \App\Command\TestDatabaseCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\TestDatabaseCommand'] = $instance = new \App\Command\TestDatabaseCommand();

        $instance->setName('TestDatabaseCommand');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
