<?php

namespace ContainerTjRJaqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestDbControllerCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\TestDbControllerCommand' shared autowired service.
     *
     * @return \App\Command\TestDbControllerCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\TestDbControllerCommand'] = $instance = new \App\Command\TestDbControllerCommand();

        $instance->setName('TestDbController');
        $instance->setDescription('Add a short description for your command');

        return $instance;
    }
}
