<?php

namespace ContainerTjRJaqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserProfileServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\service\UserProfileService' shared autowired service.
     *
     * @return \App\service\UserProfileService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\service\\UserProfileService'] = new \App\service\UserProfileService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));
    }
}
