<?php

namespace ContainerCs3hNgk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_CXL82muService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CXL82mu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CXL82mu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'travelStory' => ['privates', '.errored..service_locator.CXL82mu.App\\Entity\\TravelStory', NULL, 'Cannot autowire service ".service_locator.CXL82mu": it needs an instance of "App\\Entity\\TravelStory" but this type has been excluded in "config/services.yaml".'],
        ], [
            'travelStory' => 'App\\Entity\\TravelStory',
        ]);
    }
}
