<?php

namespace ContainerTjRJaqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_P9Im7RwService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P9Im7Rw' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P9Im7Rw'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'gemini' => ['privates', 'App\\service\\GeminiService', 'getGeminiServiceService', true],
            'request' => ['privates', '.errored._AszDvk', NULL, 'Cannot determine controller argument for "App\\Controller\\user\\ChatController::chat()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\user\\Request". Did you forget to add a use statement?'],
        ], [
            'em' => '?',
            'gemini' => 'App\\service\\GeminiService',
            'request' => '?',
        ]);
    }
}
