<?php

namespace ContainerTjRJaqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\user\AuthController' shared autowired service.
     *
     * @return \App\Controller\user\AuthController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\user\\AuthController'] = $instance = new \App\Controller\user\AuthController();

        $instance->setAuthService(new \App\service\AuthService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService'))));
        $instance->setSecurity(($container->privates['security.helper'] ?? $container->load('getSecurity_HelperService')));
        $instance->setPreferenceService(($container->privates['App\\service\\PreferenceService'] ?? $container->load('getPreferenceServiceService')));
        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\user\\AuthController', $container));

        return $instance;
    }
}
