<?php

namespace ContainerTjRJaqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getChatControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\user\ChatController' shared autowired service.
     *
     * @return \App\Controller\user\ChatController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\user\\ChatController'] = $instance = new \App\Controller\user\ChatController();

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\user\\ChatController', $container));

        return $instance;
    }
}
