<?php

namespace ContainerTjRJaqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFixAdminCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\FixAdminCommand' shared autowired service.
     *
     * @return \App\Command\FixAdminCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->privates['App\\Command\\FixAdminCommand'] = $instance = new \App\Command\FixAdminCommand(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService')));

        $instance->setName('app:fix-admin');
        $instance->setDescription('Creates or fixes the admin user');

        return $instance;
    }
}
