<?php

namespace ContainerTjRJaqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPreferenceServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\service\PreferenceService' shared autowired service.
     *
     * @return \App\service\PreferenceService
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\service\\PreferenceService'] = new \App\service\PreferenceService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')));
    }
}
