<?php

namespace ContainerTjRJaqx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestDbControllerCommand_LazyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.App\Command\TestDbControllerCommand.lazy' shared service.
     *
     * @return \Symfony\Component\Console\Command\LazyCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.App\\Command\\TestDbControllerCommand.lazy'] = new \Symfony\Component\Console\Command\LazyCommand('TestDbController', [], 'Add a short description for your command', false, #[\Closure(name: 'App\\Command\\TestDbControllerCommand')] fn (): \App\Command\TestDbControllerCommand => ($container->privates['App\\Command\\TestDbControllerCommand'] ?? $container->load('getTestDbControllerCommandService')));
    }
}
