<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Destination extends \App\Entity\Destination implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'destinationId', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'bestSeason', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'timezone', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'averageRating', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'imageUrl', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'latitude', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'longitude', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'estimatedBudget', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'popularity'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'destinationId', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'name', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'type', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'country', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'city', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'bestSeason', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'timezone', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'averageRating', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'imageUrl', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'latitude', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'longitude', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'estimatedBudget', '' . "\0" . 'App\\Entity\\Destination' . "\0" . 'popularity'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Destination $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getDestinationId(): ?string
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getDestinationId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDestinationId', []);

        return parent::getDestinationId();
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName(?string $name): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        return parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(?string $type): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getCountry(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCountry', []);

        return parent::getCountry();
    }

    /**
     * {@inheritDoc}
     */
    public function setCountry(?string $country): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCountry', [$country]);

        return parent::setCountry($country);
    }

    /**
     * {@inheritDoc}
     */
    public function getCity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCity', []);

        return parent::getCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCity(?string $city): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCity', [$city]);

        return parent::setCity($city);
    }

    /**
     * {@inheritDoc}
     */
    public function getBestSeason(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBestSeason', []);

        return parent::getBestSeason();
    }

    /**
     * {@inheritDoc}
     */
    public function setBestSeason(?string $bestSeason): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBestSeason', [$bestSeason]);

        return parent::setBestSeason($bestSeason);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(?string $description): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimezone(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimezone', []);

        return parent::getTimezone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimezone(?string $timezone): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimezone', [$timezone]);

        return parent::setTimezone($timezone);
    }

    /**
     * {@inheritDoc}
     */
    public function getAverageRating(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAverageRating', []);

        return parent::getAverageRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setAverageRating(string $averageRating): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAverageRating', [$averageRating]);

        return parent::setAverageRating($averageRating);
    }

    /**
     * {@inheritDoc}
     */
    public function getImageUrl(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageUrl', []);

        return parent::getImageUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageUrl(?string $imageUrl): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageUrl', [$imageUrl]);

        return parent::setImageUrl($imageUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getLatitude(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLatitude', []);

        return parent::getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLatitude(?string $latitude): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLatitude', [$latitude]);

        return parent::setLatitude($latitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getLongitude(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLongitude', []);

        return parent::getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    public function setLongitude(?string $longitude): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLongitude', [$longitude]);

        return parent::setLongitude($longitude);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstimatedBudget(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstimatedBudget', []);

        return parent::getEstimatedBudget();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstimatedBudget(?string $estimatedBudget): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstimatedBudget', [$estimatedBudget]);

        return parent::setEstimatedBudget($estimatedBudget);
    }

    /**
     * {@inheritDoc}
     */
    public function getPopularity(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPopularity', []);

        return parent::getPopularity();
    }

    /**
     * {@inheritDoc}
     */
    public function setPopularity(int $popularity): static
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPopularity', [$popularity]);

        return parent::setPopularity($popularity);
    }

}
