<?php

namespace ContainerCVPexdd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HGK3GJEService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HGK3GJE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HGK3GJE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'travelStory' => ['privates', '.errored..service_locator.HGK3GJE.App\\Entity\\TravelStory', NULL, 'Cannot autowire service ".service_locator.HGK3GJE": it needs an instance of "App\\Entity\\TravelStory" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'slugger' => '?',
            'travelStory' => 'App\\Entity\\TravelStory',
        ]);
    }
}
