<?php

namespace ContainerCVPexdd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZH9ApEfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZH9ApEf' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'authUtils' => ['privates', 'security.authentication_utils', 'getSecurity_AuthenticationUtilsService', true],
            'security' => ['privates', 'security.helper', 'getSecurity_HelperService', true],
        ], [
            'authUtils' => '?',
            'security' => '?',
        ]);

        if (isset($container->privates['.service_locator.ZH9ApEf'])) {
            return $container->privates['.service_locator.ZH9ApEf'];
        }

        return $container->privates['.service_locator.ZH9ApEf'] = $instance;
    }
}
