<?php

namespace ContainerCVPexdd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFrontControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\user\FrontController' shared autowired service.
     *
     * @return \App\Controller\user\FrontController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'framework-bundle'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AbstractController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'user'.\DIRECTORY_SEPARATOR.'FrontController.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'service'.\DIRECTORY_SEPARATOR.'UserProfileService.php';

        $container->services['App\\Controller\\user\\FrontController'] = $instance = new \App\Controller\user\FrontController(new \App\service\UserProfileService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['security.user_password_hasher'] ?? $container->load('getSecurity_UserPasswordHasherService'))), ($container->privates['App\\service\\DestinationService'] ?? $container->load('getDestinationServiceService')), ($container->privates['App\\service\\ActivityService'] ?? $container->load('getActivityServiceService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\user\\FrontController', $container));

        return $instance;
    }
}
