<?php

namespace ContainerCVPexdd;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTravelStoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.CXL82mu.App\Entity\TravelStory' shared service.
     *
     * @return \App\Entity\TravelStory
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.CXL82mu": it needs an instance of "App\\Entity\\TravelStory" but this type has been excluded in "config/services.yaml".');
    }
}
