<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOfKhxAt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOfKhxAt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOfKhxAt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOfKhxAt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOfKhxAt\App_KernelDevDebugContainer([
    'container.build_hash' => 'OfKhxAt',
    'container.build_id' => '6e0a56b3',
    'container.build_time' => 1775217292,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOfKhxAt');
