<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCs3hNgk\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCs3hNgk/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCs3hNgk.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCs3hNgk\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerCs3hNgk\App_KernelDevDebugContainer([
    'container.build_hash' => 'Cs3hNgk',
    'container.build_id' => '7027b62c',
    'container.build_time' => 1775833716,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCs3hNgk');
